language: go

go:
  - 1.6

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/satori/go.uuid
  - go get gopkg.in/redis.v3
  - go get github.com/gorilla/mux
  - go get github.com/shopspring/decimal

services:
  - redis
  - mysql

before_install:
  - bash ./travis/build.sh

script: go test -v accounts/ && go test -v appauth/ && go test -v payments/
